### ISSUE TITLE
403 for getFileUploadUrl

### ISSUE THREAD

**Issue by kibotu** [ferPrieto/steps-app-gallery-deploy#19]
first of all thanks a lot for your step.sh :) 

when i run the script it succeeds to retrieve access token by using `getToken` method, however when running `getFileUploadUrl` it fails with 403

any idea why? 

`
Obtaining the File Upload URL
+ curl -v -X GET 'https://connect-api.cloud.huawei.com/api/publish/v2/upload-url?appId=reducted-app-id&suffix=aab&releaseType=1' -H 'Authorization: Bearer reducted-access-token' -H 'Content-Type: application/json' -H 'client_id: reducted-client-id'
Note: Unnecessary use of -X or --request, GET is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.222.236.99...
* TCP_NODELAY set
* Connected to connect-api.cloud.huawei.com (52.222.236.99) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [242 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [91 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [3117 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=CN; ST=Jiangsu; L=Nanjing; OU=Cloud Platform GLOBAL Dept; O=Huawei Software Technologies Co., Ltd.; CN=cloud.huawei.com
*  start date: Aug 25 00:42:13 2020 GMT
*  expire date: Aug 26 00:42:13 2022 GMT
*  subjectAltName: host "connect-api.cloud.huawei.com" matched cert's "*.cloud.huawei.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify ok.
> GET /api/publish/v2/upload-url?appId=reducted-app-id&suffix=aab&releaseType=1 HTTP/1.1
> Host: connect-api.cloud.huawei.com
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer reducted-access-token
> Content-Type: application/json
> client_id: reducted-client-id
> 
< HTTP/1.1 403 client token authorization fail.
< Content-Length: 0
< Connection: keep-alive
< Date: Tue, 04 Jan 2022 08:21:34 GMT
< X-Cache: Error from cloudfront
< Via: 1.1 e59bea79ab5f15feda92136bc7b74159.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: FRA56-P4
< X-Amz-Cf-Id: 9zqgSWZeoVJ_aqdy9MYxUS0CiRyXX_ZWTYa93wGIHuY9ayoym22OzQ==
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host connect-api.cloud.huawei.com left intact
* Closing connection 0
+ cat uploadurl.json
`

**Comment by kibotu** [comment]
Ok turns out I created api key incorrectly. I've added a screenshot to highlight this issue also added documentation link. #20 cheers~

**Comment by ferPrieto** [comment]
Perfect @kibotu, thanks for letting me know 👍🏽
