### ISSUE TITLE
(fyi) i've ported submitting to groovy :) 

### ISSUE THREAD

**Issue by kibotu** [ferPrieto/steps-app-gallery-deploy#21]
thanks for your great help with your repo! learned a lot. my company uses different ci tools and i ported the scripts to gradle

https://gist.github.com/kibotu/dbcf2fe338f2e2530980f753608288d6

**Comment by ferPrieto** [comment]
Nice one Jan🥇!! 
You should create that plugin publicly on Github, so people can use it in their projects too .
