### ISSUE TITLE
appgallery-deploy@1 (exit code: 6)  

### ISSUE THREAD

**Issue by bmagnien-accor** [ferPrieto/steps-app-gallery-deploy#23]
![image](https://user-images.githubusercontent.com/60108950/154446767-c6ef0d8c-26f5-457b-8116-ddc7f0834e54.png)

Anyone know what Exit code: 6 stands for ? 
Any help would be really appreciated :) 

Thanks for this awesome bitrise step !

**Comment by ferPrieto** [comment]
Hey @bmagnien-accor it's very likely that there's some issue about what it's expected in the Bitrise Step: you must be setting a file name with` .apk` and gradle could be building an`.aab.` You can check this value in your `Huawei Step` (within your workflow) 👇🏽
<p align="center">
<img src="https://user-images.githubusercontent.com/5220412/153673085-c3afe7f9-2eab-49c3-a67a-139cd28561e8.png"/> 
</p>

Another reason could be that you're exceeding the file max size stablished:

- APK file: The size cannot exceed 4 GB.
- RPK file: The size cannot exceed 20 MB.
- AAB file: The size cannot exceed 150 MB.

**Comment by bmagnien-accor** [comment]
Hey, thanks for your fast answer ! 
I've set a correct file path (set to `$BITRISE_SIGNED_APK_PATH`, provided by the "Android sign" bitrise plugin. This should be correct.

I've set the file name to its default value app_release_${BITRISE_BUILD_NUMBER}.apk because i'm okay with this name.
... And my APK size is 74mo

Still, I'm having the Exit code 6 error 🤔 

Does this error code come from the Huawei API ? Because I can't find any information on the official Huawei documentation https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agcapi-upload_appfile-0000001158365309

**Comment by ferPrieto** [comment]
@bmagnien-accor The error code is retrieved from the [Uploading File call](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agcapi-upload-file-0000001158245059)
I assume that you already published a release version manually at least once? Otherwise this could be the cause.
The rest of parameters seem correct though.

You can always contact Huawei to get more info about that and they can check in their end what's going on with your app.

**Comment by bmagnien-accor** [comment]
Yes we already have a bunch of release on the App Gallery

I'm currently trying to deploy the app to the chinese AppGallery, and I think this might be the cause. It takes ages even when I upload manually my apk the the website. 
Perhaps the API is not available / fast enough with chinese servers.

We're currently migrating the app from Huawei China to Huawei Europe server. I'll try again once it's done.
If it doesn't fix my issue, I'll contact Huawei for sure. 

I'll put the solution here when I find out 😉 

Thank's a lot for your help, and have a great day !

**Comment by ferPrieto** [comment]
Releasing in `China mainland` is always a different process compared to the `West Europe` and probably as you mentioned the uploading process gets affected by that. Please keep me posted and hopefully this gets sorted out soon!
Have a great one too @bmagnien-accor 👍🏽

**Comment by ferPrieto** [comment]
Closed due to inactivity
